Fixes - everywhere.

diff --git a/bin/dots b/bin/dots
--- a/bin/dots
+++ b/bin/dots
@@ -19,12 +19,9 @@ set -g DOTS_LIBEXEC $DOTS/libexec/dots
 # FIXME: check for DOTS before using
 source $DOTS_LIBEXEC/common-lib.fish
 or begin
-    echo "FATAL: could not source common-lib.fish -- exiting program..."
+    echo "FATAL: could not source common-lib.fish -- exiting program..." 1>&2
     exit 11
 end
-
-# check the rest of our minimal config assumptions
-dots_require_base_config
 
 # all this script does is serve as a front-end to others
 # we can assume that dots-bootstrap.sh has already run.
@@ -54,9 +51,12 @@ function main
     end
 
     if set -q _flag_version
-        echo (status basename) v$VERSION
+        echo (status basename) v$DOTS_VERSION
         exit 0
     end
+
+    # check the rest of our minimal config assumptions
+    dots_require_base_config
 
     if set -q argv[1]
         # First arg is a subcmd - it needs to exist in $DOTS_LIBEXEC
diff --git a/libexec/dots/linker b/libexec/dots/linker
--- a/libexec/dots/linker
+++ b/libexec/dots/linker
@@ -19,17 +19,21 @@ end
 # FIXME: check for DOTS before using
 source $DOTS_LIBEXEC/common-lib.fish
 or begin
-    echo "FATAL: could not source common-lib.fish -- exiting program..."
+    echo "FATAL: could not source common-lib.fish -- exiting program..." 1>&2
     exit 11
 end
 
 function install_dotfiles
     # info 'installing dotfiles'
 
-    for src in (find -H "$DOTS" "$DOTS_LOCAL" -maxdepth 2 -name '*.symlink' -not -path '*.git*')
+    #    for src in (find -H "$DOTS" "$DOTS_LOCAL" -maxdepth 2 -name '*.symlink' -not -path '*.git*')
+    set symlinks (string split ' ' (dots_files_with_active_profile .symlink )) $DOTS_LOCAL/*.symlink
+    for src in $symlinks
+        # Convert the src roughly into the dest
+        set dst $HOME/.(string replace -r '\.symlink$' '' (basename $src))
 
-        # dst="$HOME/.$(basename "${src%.*}")"
-        set -l dst $HOME/.(string replace -r '\.symlink$' '' (basename $src))
+        # Sadly, we can't just dump everything in $HOME anymore ... ~/.config is a thing and so is ~/.ssh
+        set dst (string replace -a % / $dst)
         echo ln -s $src $dst
 
     end
@@ -37,10 +41,22 @@ function install_dotfiles
 end
 
 function main
-    install_dotfiles
+    argparse --name (status basename) debug h/help -- $argv
+    or begin
+        echo $HELP
+        exit 1
+    end
 
-    echo ''
-    echo '  All installed!'
+    if set -q _flag_debug
+        set -g FLAG_DEBUG true
+    end
+
+    if set -q _flag_help
+        echo $HELP
+        exit 0
+    end
+
+    install_dotfiles
 end
 
 main $argv
