Fix formatting

diff --git a/libexec/dots/check b/libexec/dots/check
--- a/libexec/dots/check
+++ b/libexec/dots/check
@@ -1,20 +1,19 @@
-#! /usr/bin/env fish  
+#! /usr/bin/env fish
 
 set help "
 Usage: dots builder [options] suffix target_file
 Options:
-  -d, --debug        Enable debug mode
-  -h, --help         Show this help
+    -d, --debug        Enable debug mode
+    -h, --help         Show this help
 "
 
-source $DOTS/libexec/dots/lib-common.fish
+source $DOTS/libexec/dots/common-lib.fish
 or begin
-	echo "FATAL: Unable to source lib-common.fish library" 
-	exit 10
+    echo "FATAL: Unable to source common-lib.fish library"
+    exit 10
 end
 
 # this script exists solely to call the dots_verify_base_config function in lib-common.fish
 dots_verify_base_config
 
 ## END OF LINE ##
-
diff --git a/libexec/dots/fishconfig b/libexec/dots/fishconfig
--- a/libexec/dots/fishconfig
+++ b/libexec/dots/fishconfig
@@ -1,16 +1,16 @@
-#! /usr/bin/env fish  
+#! /usr/bin/env fish
 
 set help "
 Usage: dots builder [options] suffix target_file
 Options:
-  -d, --debug        Enable debug mode
-  -h, --help         Show this help
+    -d, --debug        Enable debug mode
+    -h, --help         Show this help
 "
 
-source $DOTS/libexec/dots/lib-common.fish
+source $DOTS/libexec/dots/common-lib.fish
 or begin
-	echo "FATAL: Unable to source lib-common.fish library" 
-	exit 10
+    echo "FATAL: Unable to source common-lib.fish library"
+    exit 10
 end
 
-dots builder .fish $DOTS_L/config%fish%config.fish.symlink
+dots builder .fish $DOTS_LOCAL/config%fish%config.fish.symlink
diff --git a/libexec/dots/sshconfig b/libexec/dots/sshconfig
--- a/libexec/dots/sshconfig
+++ b/libexec/dots/sshconfig
@@ -1,24 +1,24 @@
-#! /usr/bin/env fish  
+#! /usr/bin/env fish
 
 set help "
 Usage: dots builder [options] suffix target_file
 Options:
-  -d, --debug        Enable debug mode
-  -h, --help         Show this help
+    -d, --debug        Enable debug mode
+    -h, --help         Show this help
 "
 
-source $DOTS/libexec/dots/lib-common.fish
+source $DOTS/libexec/dots/common-lib.fish
 or begin
-	echo "FATAL: Unable to source lib-common.fish library" 
-	exit 10
+    echo "FATAL: Unable to source common-lib.fish library"
+    exit 10
 end
 
 echo "ERROR: This script is not yet implemented."
 exit 1
 
-Consider this, or just moving the ssh configs around a bit
-mostly in the work_profile....
+# Consider this, or just moving the ssh configs around a bit
+# mostly in the work_profile....
 
-dots builder --dir $DOTS/ssh/config.d --no-profile .conf .$DOTS_L/ssh%config.symlink
+dots builder .conf $DOTS_LOCAL/ssh%config.symlink
 
 # END OF LINE  #
