Convert holmans old script/bootstrap script to fish and rename it as part of "dots"
https://github.com/holman/dotfiles/blob/master/script/bootstrap

diff --git a/libexec/dots/linker b/libexec/dots/linker
--- a/libexec/dots/linker
+++ b/libexec/dots/linker
@@ -1,138 +1,48 @@
-#! /usr/bin/env bash
-#
-# make symlinks for *.symlink files.
+#! /usr/bin/env fish
 
-cd "$(dirname "$0")/.."
-DOTFILES_ROOT=$(basename $PWD)
-#echo DOTFILES_ROOT = $DOTFILES_ROOT
+set -g HELP "
+Usage: $(status basename) [options...]
 
-set -e
+make symlinks for *.symlink files.
 
-echo ''
+Optional Arguments
+        --debug              Print debug information
+    -h, --help               Print this help
+"
 
-info () {
-    printf "  [ \033[00;34m..\033[0m ] $1"
-}
+set -g DOTS_LIBEXEC $DOTS/libexec/dots
+# TODO: migrate this to the common-lib ...
+function fish_command_not_found
+    exit 12
+end
 
-user () {
-    printf "\r  [ \033[0;33m?\033[0m ] $1 "
-}
+# FIXME: check for DOTS before using
+source $DOTS_LIBEXEC/common-lib.fish
+or begin
+    echo "FATAL: could not source common-lib.fish -- exiting program..."
+    exit 11
+end
 
-success () {
-    printf "\r\033[2K  [ \033[00;32mOK\033[0m ] $1\n"
-}
+function install_dotfiles
+    # info 'installing dotfiles'
 
-fail () {
-    printf "\r\033[2K  [\033[0;31mFAIL\033[0m] $1\n"
+    for src in (find -H "$DOTS" "$DOTS_LOCAL" -maxdepth 2 -name '*.symlink' -not -path '*.git*')
+
+        # dst="$HOME/.$(basename "${src%.*}")"
+        set -l dst $HOME/.(string replace -r '\.symlink$' '' (basename $src))
+        echo ln -s $src $dst
+
+    end
+
+end
+
+function main
+    install_dotfiles
+
     echo ''
-    exit
-}
+    echo '  All installed!'
+end
 
-link_file () {
-    local src=$1 dst=$2
+main $argv
 
-    # echo src = $src
-    # echo dst = $dst
-
-    local overwrite= backup= skip=
-    local action=
-
-    if [ -f "$dst" -o -d "$dst" -o -L "$dst" ]
-    then
-
-        if [ "$overwrite_all" == "false" ] && [ "$backup_all" == "false" ] && [ "$skip_all" == "false" ]
-        then
-
-            local currentSrc="$(readlink $dst)"
-
-            if [ "$currentSrc" == "$src" ]
-            then
-
-                skip=true;
-
-            else
-
-                user "File already exists: $(basename "$src"), what do you want to do? [s]kip, [S]kip all, [o]verwrite, [O]verwrite all, [b]ackup, [B]ackup all?"
-                read -n 1 action
-
-                case "$action" in
-                    o )
-                        overwrite=true;;
-                    O )
-                        overwrite_all=true;;
-                    b )
-                        backup=true;;
-                    B )
-                        backup_all=true;;
-                    s )
-                        skip=true;;
-                    S )
-                        skip_all=true;;
-                    * )
-                        ;;
-                esac
-
-            fi
-
-        fi
-
-        overwrite=${overwrite:-$overwrite_all}
-        backup=${backup:-$backup_all}
-        skip=${skip:-$skip_all}
-
-        if [ "$overwrite" == "true" ]
-        then
-            rm -rf "$dst"
-            success "removed $dst"
-        fi
-
-        if [ "$backup" == "true" ]
-        then
-            mv "$dst" "${dst}.backup"
-            success "moved $dst to ${dst}.backup"
-        fi
-
-        if [ "$skip" == "true" ]
-        then
-            success "skipped $src"
-        fi
-    fi
-
-    if [ "$skip" != "true" ]  # "false" or empty
-    then
-        ln -s "$1" "$2"
-        success "linked $1 to $2"
-    fi
-}
-
-install_dotfiles () {
-    info 'installing dotfiles'
-
-    local overwrite_all=false backup_all=false skip_all=false
-
-    cd ..               ## state - we were in .dotfiles (see top of script)
-                        ## with luck, this will work for glacierhomes
-                        ## due to that, you cant use $HOME
-    # echo "creating symlink in $PWD"
-    for src in $(find "$DOTFILES_ROOT" -maxdepth 2 -name '*.symlink')
-    do
-        dst=".$(basename "${src%.*}")"
-        link_file "$src" "$dst"
-    done
-
-    # Special case - I wanted bin symlinked into home, but NOT hidden
-    for src in $(find "$DOTFILES_ROOT" -maxdepth 2 -name '*.symlink_nodot')
-    do
-        dst="$(basename "${src%.*}")"
-        link_file "$src" "$dst"
-    done
-
-    link_file ".dotfiles/bin" "bin"
-    link_file "../.dotfiles/ssh/config" ".ssh/config"
-
-}
-
-install_dotfiles
-
-echo ''
-echo '  All installed!'
+# END OF LINE #
